### ISSUE TITLE
Error in Query Response when Using Relationship in v1.0.0-alpha.16

### ISSUE THREAD

**Issue by cleicastro** [typicode/json-server#1480]
I'm currently working with version 1.0.0-alpha.16, and I've encountered an error in the query response when attempting to use relationships.

**Comment by typicode** [comment]
Hi, could you please provide a failing example? (route and db)

**Comment by cleicastro** [comment]
Error: TypeError: query._embed?.forEach is not a function
    at Service.findById
    
Route: http://localhost:3000/orders/1?_embed=shifts

**Comment by typicode** [comment]
Thank you. Fixed in `alpha.19`
